# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('projetos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'escolha',
                'verbose_name_plural': 'escolhas',
            },
        ),
        migrations.CreateModel(
            name='InitialListQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Nome da lista')),
                ('select', models.IntegerField(default=0)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.Projeto')),
                ('questions', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name=b'Quest\xc3\xb5es')),
            ],
            options={
                'verbose_name': 'Lista de Quest\xf5es para o Home',
                'verbose_name_plural': 'Lista de Quest\xf5es para o Home',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[(b'1', b'One choice'), (b'2', b'Multipla Escolha'), (b'3', b'Texto')], max_length=1, verbose_name=b'Tipo')),
                ('question_text', models.CharField(max_length=200, verbose_name=b'T\xc3\xadtulo da Quest\xc3\xa3o')),
                ('publ_date', models.DateTimeField(verbose_name=b'Data de publica\xc3\xa7\xc3\xa3o')),
                ('exp_date', models.DateTimeField(verbose_name=b'Data de expira\xc3\xa7\xc3\xa3o')),
                ('days', models.IntegerField(choices=[(1, b'1 dia'), (7, b'1 semana'), (30, b'1 m\xc3\xaas'), (365, b'1 ano'), (3650, b'Indeterminado')], default=3650, verbose_name=b'Tempo para expirar')),
                ('question_status', models.CharField(choices=[(b'n', b'N\xc3\xa3o publicado'), (b'p', b'Publicado')], default=b'n', max_length=1, verbose_name=b'Estado da quest\xc3\xa3o')),
                ('answer_status', models.CharField(choices=[(b'n', b'N\xc3\xa3o publicado'), (b'p', b'Publicado')], default=b'n', max_length=1, verbose_name=b'Estado da resposta')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'question_images', verbose_name=b'Imagem')),
                ('address', models.CharField(max_length=200, verbose_name=b'Endere\xc3\xa7o')),
                ('permissao', models.IntegerField(default=0)),
                ('resultado', models.CharField(choices=[(b'n', b'N\xc3\xa3o publicado'), (b'p', b'Publicado')], default=b'n', max_length=1)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.Projeto')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'quest\xe3o',
                'verbose_name_plural': 'quest\xf5es',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agora.Question'),
        ),
    ]
