# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(blank=True, default='def', max_length=100, verbose_name='Projeto')),
                ('sigla', models.CharField(blank=True, default='def', max_length=50, verbose_name='Sigla')),
            ],
        ),
    ]
