# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='projeto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='sigla',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla'),
        ),
    ]
