# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_topic_projeto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='pub_date',
            new_name='publ_date',
        ),
    ]
