# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20160518_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
