# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20160518_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'debate', 'verbose_name_plural': 'debates'},
        ),
    ]
