# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 17:57
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('projetos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name=b'T\xc3\xadtulo do artigo')),
                ('article', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descri\xe7\xe3o')),
                ('publ_date', models.DateTimeField(verbose_name=b'Data de publica\xc3\xa7\xc3\xa3o')),
                ('destaque', models.CharField(default=b'N\xc3\xa3o', max_length=3, verbose_name=b'Destacado?')),
                ('questao_associada', models.CommaSeparatedIntegerField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=200, verbose_name=b'Endere\xc3\xa7o')),
                ('published', models.CharField(default=b'N\xc3\xa3o', max_length=3, verbose_name=b'Publicado?')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.Projeto')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('url_title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SubTopico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopico_nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Sub-topico',
                'verbose_name_plural': 'Sub-t\xf3picos',
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(max_length=200)),
                ('address_topico', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=1)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.Projeto')),
            ],
            options={
                'verbose_name': 'T\xf3pico',
                'verbose_name_plural': 'T\xf3picos',
            },
        ),
        migrations.AddField(
            model_name='subtopico',
            name='subtopico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conheca.Topico'),
        ),
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conheca.SubTopico'),
        ),
    ]
