# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '__first__'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('agora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=200, null=True)),
                ('answer_date', models.DateTimeField(editable=False)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='agora.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='agora.Question')),
            ],
            options={
                'verbose_name': 'resposta',
                'verbose_name_plural': 'respostas',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.CharField(default='Nao', max_length=3, verbose_name='Publicado?')),
                ('kind', models.CharField(choices=[('1', 'Conhe\xe7a'), ('2', 'Resultados'), ('3', 'Comunidade'), ('4', 'Participe')], max_length=1, verbose_name='Tipo')),
                ('publ_date', models.DateTimeField(verbose_name='Data de publica\xe7\xe3o')),
                ('message', models.CharField(max_length=500, verbose_name='Recado')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Endere\xe7o')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.Projeto')),
            ],
        ),
        migrations.CreateModel(
            name='MeuEspaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(max_length=20, verbose_name='Projeto')),
                ('user', models.CharField(blank=True, max_length=200, verbose_name='Usuario')),
                ('categoria', models.CharField(blank=True, max_length=20, verbose_name='Categoria')),
                ('publ_date', models.DateTimeField(verbose_name='Data de publica\xe7\xe3o')),
                ('link', models.URLField(blank=True, max_length=1000)),
                ('comentario', models.CharField(blank=True, max_length=200, verbose_name='Coment\xe1rio')),
                ('secao', models.CharField(blank=True, max_length=30, verbose_name='Se\xe7\xe3o')),
                ('arquivo', models.FileField(blank=True, max_length=2000000, upload_to=b'C:\\virtual-agora\\media')),
            ],
        ),
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(default='Nao', max_length=10, verbose_name='Condi\xe7\xe3o')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('primeiro_nome', models.CharField(blank=True, max_length=40, verbose_name='Primeiro nome')),
                ('ultimo_nome', models.CharField(blank=True, max_length=100, verbose_name='Sobrenome')),
                ('staff', models.CharField(blank=True, choices=[('1', 'Professor'), ('2', 'Funcion\xe1rio'), ('3', 'Aluno'), ('4', 'Outro')], max_length=1, verbose_name='Staff')),
                ('year_of_start', models.IntegerField(blank=True, default='9999', verbose_name='Ano de ingresso')),
                ('course', models.CharField(blank=True, default='curso', max_length=40, verbose_name='Curso')),
                ('institute', models.CharField(blank=True, default='instituto', max_length=40, verbose_name='Instituto')),
                ('academic_registry', models.IntegerField(default='9999', verbose_name='Registro acad\xeamico')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('nickname', models.CharField(blank=True, max_length=40, verbose_name='Apelido')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.Projeto')),
                ('question_answer', models.ManyToManyField(related_name='question_answer', through='agoraunicamp.Answer', to='agora.Question')),
            ],
            options={
                'verbose_name': 'usu\xe1rio',
                'verbose_name_plural': 'usu\xe1rios',
            },
        ),
        migrations.AddField(
            model_name='termo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_termo', to='agoraunicamp.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='agoraunicamp.User'),
        ),
    ]
