# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='projeto',
            field=models.CharField(blank=True, max_length=40, verbose_name='Projeto'),
        ),
    ]
