# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0002_auto_20160415_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='address',
            field=models.CharField(blank=True, default='opcional', max_length=200, verbose_name='Endere\xe7o'),
        ),
    ]
