# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0003_auto_20160418_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Nao', max_length=10, verbose_name='Status')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='academic_registry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year_of_start',
        ),
        migrations.AlterField(
            model_name='meuespaco',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='meuespaco',
            name='comentario',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Coment\xe1rio'),
        ),
        migrations.AlterField(
            model_name='meuespaco',
            name='projeto',
            field=models.CharField(max_length=100, verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.CharField(blank=True, choices=[('1', 'Professor'), ('2', 'Funcion\xe1rio'), ('3', 'Aluno-Graduacao'), ('4', 'Aluno-Mestrado'), ('5', 'Aluno-Doutorado'), ('6', 'Aluno-Especial'), ('7', 'Aluno-Lato'), ('8', 'outro')], max_length=1, verbose_name='Staff'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agoraunicamp.User'),
        ),
    ]
