# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0004_auto_20160516_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='status',
            field=models.CharField(default='nao', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.CharField(blank=True, choices=[('1', 'Professor'), ('2', 'Funcionario'), ('3', 'Aluno-Graduacao'), ('4', 'Aluno-Mestrado'), ('5', 'Aluno-Doutorado'), ('6', 'Aluno-Especial'), ('7', 'Aluno-Lato'), ('8', 'outro')], max_length=1, verbose_name='Staff'),
        ),
    ]
