# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0005_auto_20160517_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuespaco',
            name='arquivo',
            field=models.FileField(blank=True, max_length=2000000, upload_to=b'/home/cantarela/agora/virtual-agora-2017/media'),
        ),
    ]
