# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0003_protofrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertice', models.CharField(max_length=50, verbose_name='vertice_s')),
                ('posicao', models.IntegerField(verbose_name='posicao')),
            ],
        ),
    ]
