# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0004_sorteio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeAdjacencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertice_i', models.CharField(max_length=50, verbose_name='vi')),
                ('vertice_f', models.CharField(max_length=50, verbose_name='vf')),
                ('peso', models.IntegerField(verbose_name='peso')),
            ],
        ),
    ]
