# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0005_listadeadjacencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospreproc',
            name='quantidade_de_sentencas',
            field=models.IntegerField(default=1, verbose_name='q_sen'),
            preserve_default=False,
        ),
    ]
