# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0006_dadospreproc_quantidade_de_sentencas'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospreproc',
            name='palavras_por_sentenca_lssw',
            field=models.IntegerField(default=1, verbose_name='ppsl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadospreproc',
            name='palavras_por_sentenca_org',
            field=models.IntegerField(default=1, verbose_name='ppso'),
            preserve_default=False,
        ),
    ]
