# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0007_auto_20161119_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosProtofrases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protofrase', models.TextField(verbose_name='dpf')),
                ('repeticao', models.IntegerField(verbose_name='rep')),
            ],
        ),
    ]
