# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0008_dadosprotofrases'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospreproc',
            name='nome_rel_protofrase',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='nome_rel_pfs'),
            preserve_default=False,
        ),
    ]
