# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0009_dadospreproc_nome_rel_protofrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosMapeamentoEExtracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=100, verbose_name='arq')),
            ],
        ),
    ]
