# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0010_dadosmapeamentoeextracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosmapeamentoeextracao',
            name='protofrase',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='dpf'),
            preserve_default=False,
        ),
    ]
