# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0011_dadosmapeamentoeextracao_protofrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosmapeamentoeextracao',
            name='num_sent_docPreproc',
            field=models.IntegerField(default=1, verbose_name='nsdp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadosmapeamentoeextracao',
            name='num_sent_docPreprocLemCSW',
            field=models.IntegerField(default=1, verbose_name='nsdplc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadosmapeamentoeextracao',
            name='num_sent_docPreprocLemSSW',
            field=models.IntegerField(default=1, verbose_name='nsdpls'),
            preserve_default=False,
        ),
    ]
