# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0012_auto_20161122_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapeamentoEExtracaoTextos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragrafo', models.IntegerField(verbose_name='par')),
                ('doc_preproc', models.TextField(verbose_name='d_p')),
                ('doc_preprocLemCSSW', models.TextField(verbose_name='d_plc')),
                ('doc_preprocLemSSW', models.TextField(verbose_name='d_pls')),
            ],
        ),
    ]
