# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-22 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0013_mapeamentoeextracaotextos'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosmapeamentoeextracao',
            name='extracaoParagrafosEtapa1',
            field=models.TextField(default=1, verbose_name='etapa1'),
            preserve_default=False,
        ),
    ]
